### ISSUE TITLE
Incompatible with metalsmith-permalinks

### ISSUE THREAD

**Issue by replete** [michel-kraemer/metalsmith-brotli#1]
``` log
  if (err) { throw err; }
             ^
TypeError: Cannot read property 'contents' of undefined
    at d:\Git\replete\replete-website\node_modules\metalsmith-brotli\lib\index.js:26:26
    at d:\Git\replete\replete-website\node_modules\metalsmith-brotli\node_modules\async\dist\async.js:3047:20
    at eachOfArrayLike (d:\Git\replete\replete-website\node_modules\metalsmith-brotli\node_modules\async\dist\async.js:1002:13)
    at eachOf (d:\Git\replete\replete-website\node_modules\metalsmith-brotli\node_modules\async\dist\async.js:1052:9)
    at eachLimit (d:\Git\replete\replete-website\node_modules\metalsmith-brotli\node_modules\async\dist\async.js:3111:7)
    at Ware.<anonymous> (d:\Git\replete\replete-website\node_modules\metalsmith-brotli\lib\index.js:23:9)
    at Ware.<anonymous> (d:\Git\replete\replete-website\node_modules\wrap-fn\index.js:45:19)
    at next (d:\Git\replete\replete-website\node_modules\ware\lib\index.js:85:20)
    at d:\Git\replete\replete-website\node_modules\wrap-fn\index.js:121:18
    at d:\Git\replete\replete-website\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:52:16
    at done (d:\Git\replete\replete-website\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:246:17)
    at d:\Git\replete\replete-website\node_modules\metalsmith-layouts\node_modules\async\lib\async.js:44:16
    at d:\Git\replete\replete-website\node_modules\metalsmith-layouts\lib\index.js:143:9
    at d:\Git\replete\replete-website\node_modules\consolidate\lib\consolidate.js:734:7
    at d:\Git\replete\replete-website\node_modules\consolidate\lib\consolidate.js:143:5
    at Promise._execute (d:\Git\replete\replete-website\node_modules\bluebird\js\release\debuggability.js:299:9)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\phil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! replete-website@1.0.0 build: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the replete-website@1.0.0 build script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the replete-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs replete-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls replete-website
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     d:\Git\replete\replete-website\npm-debug.log
```

**Comment by michel-kraemer** [comment]
Hi!

Thanks for reporting the issue. I cannot reproduce it though.

I made a working example and pushed it here:
https://github.com/michel-kraemer/metalsmith-brotli-issue1

Can you please check what the difference between the example and your code is? Or can you change the example so that I can reproduce the error?

How do you know that metalsmith-permalinks is the source of the problem? Can you please elaborate?

Thanks,
Michel

**Comment by michel-kraemer** [comment]
@replete I haven't heard back from you. Is this still an issue?

**Comment by michel-kraemer** [comment]
@replete I haven't heard back from you in more than two months so I suppose the issue is fixed. I'll close it tomorrow and delete the working example.

**Comment by replete** [comment]
Sorry Michael, I moved on from metalsmith because of the issues I was encountering.

**Comment by michel-kraemer** [comment]
OK. Thanks for the feedback.

Michel
